# FE-595A
# Plot sine and cos on same axis
import matplotlib.pyplot as plt
import numpy as np

# Initialize a Figure 
fig = plt.figure()


x = np.arange(0, 2*np.pi, 0.1)

y = np.sin(x)
z = np.cos(x)

#Add tangent graph
tangent = np.tan(x)

#Remove asymptotes generated by tangent graph
tangent[:-1][np.diff(tangent) < 0] = np.nan

# Changed axis label names
plt.xlabel('Phase (radians)')
plt.ylabel('Amplitude')


plt.plot(x, y, color="red", label="sine")
plt.plot(x, z, color="blue", label="cosine")

# Add Tangent
plt.plot(x, tangent, color = "green", label = "tangent")

# Add x-axis tick label locations 
plt.xticks((0, np.pi/2, np.pi, np.pi*3/2, np.pi*2), ('0', 'π/2', 'π', '3π/2', 
           '2π'))

plt.plot(x, y, x, z, x, tangent)

#Define the X axis limits
plt.xlim((0, 2 * np.pi))

#Define the Y axis limits
plt.ylim((-1, 1))

# Add a horizontal line across the x-axis
plt.axhline(y=0, color='k')

# Add grid lines
plt.grid(color='black', linestyle='-', linewidth=0.2)

# Graph title and legend
plt.title('Sine, Cosine, and Tagent Graph')
plt.legend()

#plt.legend(['sin(x)', 'cos(x)'])
plt.show()

#Add a feature that saves the resulting graph locally
fig.savefig('Assignment2.pdf')

